title: "MedMonitor: Medical IoT Gateway"
description: "Pre-compliant Medical IoT Gateway for MIC@Home and hospital step-down wards in ASEAN"
lang: en_US

# URL Settings
url: "https://calaweh.github.io"
baseurl: "/medmonitor-iot-gateway"

# Build Settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Content Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# This ensures Jekyll looks in the docs folder correctly
include: [docs]