title: "MedMonitor: Open-Source Medical IoT Gateway"
description: "Portfolio project: IEC 62304 Class B compliant Medical IoT Telemetry Gateway built with .NET 8 and React."
theme: jekyll-theme-minimal
google_site_verification: "google4c15c6f6afe52053"